### ISSUE TITLE
encabezados modulo de contrataciones, UAI, EVCON

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#19]
*CONTRATACIONES: se debe mostrar las siguientes columnas:
NUMERO DE INFORME  (código)
DOCUMENTO ADJUNTO INFORME (Informe SCEP)
DOCUMENTO ADJUNTO NOTA EMITIDA (Nota emitida a la empresa)
GESTION
EMPRESA    
ELABORADO POR  (--este campo en lo posible que jale el nombre del usuario en uso--)

![image](https://user-images.githubusercontent.com/25138642/55727228-8bd3bf80-59df-11e9-8a45-426912d02dfc.png)

*UAI: la columna:
ELABORADO POR  (--este campo en lo posible que jale el nombre del usuario en uso--)

*EVCON: 
ELABORADO POR  (--este campo en lo posible que jale el nombre del usuario en uso--)
SUPERVISOR (--se debe escoger de la tabla de usuarios--)
![image](https://user-images.githubusercontent.com/25138642/55727451-056bad80-59e0-11e9-999a-7d540d3bbbcf.png)

* David es posible ordenar el campo de seleccion de empresas en UAI, EVCON, y CONTRATACIONES  con algo similar a esto:???
![image](https://user-images.githubusercontent.com/25138642/55727816-d1dd5300-59e0-11e9-99e7-df00e6dc4f18.png)
porque tardamos mucho en buscar en toda la base de datos de las empresas

**Comment by caleeli** [comment]
Se ajustaron las etiquetas
![image](https://user-images.githubusercontent.com/8028650/55767908-c02f9600-5a48-11e9-85ec-924ff7296d56.png)

**Comment by caleeli** [comment]
Se agregaron los nuevos campos:
*UAI:
ELABORADO POR

*EVCON:
ELABORADO POR
SUPERVISOR


![image](https://user-images.githubusercontent.com/8028650/64113696-f30c5a80-cd58-11e9-91e4-814ae46473b9.png)
