### ISSUE TITLE
Agregar controles Hoja de Ruta

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#27]
- Agregar un usuario: mvargas pass:1234567
- Modificar usuario "mary" por "mtorrez"
Todos los permisos para estos dos usuarios: mtorrez y mvargas
- Agregar la opcion de eliminar una derivación: donde marque con lapiz azul, porque algunas veces hacen dobles registros, ya existe la modificacion pero no la eliminación.
![imagen](https://user-images.githubusercontent.com/25138642/61808574-aa808980-ae09-11e9-8e89-9764a480686e.png)
- Agregar un boton para habilitar la hoja de ruta, en caso de haberla cerrado por alguna razon (esto es algo que se le presenta con regularidad por las indecisiones del subcontralor): 
![imagen](https://user-images.githubusercontent.com/25138642/61809138-bae53400-ae0a-11e9-8d37-dbbc48f5bc32.png)

**Comment by caleeli** [comment]
Se agrego una pantalla para cambio de contraseña

![image](https://user-images.githubusercontent.com/8028650/61878327-d0b43100-aebe-11e9-84f6-cc2cf7830d87.png)

Se agrego la tabla usuarios:
![image](https://user-images.githubusercontent.com/8028650/61878364-dc075c80-aebe-11e9-9c87-41360a599e63.png)

**Comment by caleeli** [comment]
se cambio el usuario **mary** -> **mtorrez**
se creo el usuario **mvargas**
