### ISSUE TITLE
Hoja de ruta arreglos

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#29]
- En notas oficio, el boton de exportar a excel no exporta no realiza ninguna accion:
![imagen](https://user-images.githubusercontent.com/25138642/62135543-65000880-b2b0-11e9-8a9f-4fbabf812a5c.png)
- Sacando un reporte de Oficio... como de su nota recibida (respuesta) me genera solo la nota oficio enviada y no la respuesta, en este caso se busco en Oficio:(Empresa: ofep), y nota recibida: (remitente: Ana), deberia haber 3 notas emitidas y 1 con respuesta, pero me sale solo las enviadas:

![imagen](https://user-images.githubusercontent.com/25138642/62135642-924cb680-b2b0-11e9-81ab-46f3f642a092.png)

- No genera reportes las "comunicaciones internas" que deberian ser igual a las notas oficio, tienen la misma forma de enviarlas y esperar las respuestas

**Comment by caleeli** [comment]
Podrías indicarme cual es la _nota de respuesta_ que no esta saliendo o en que campo se registra, para que en base a esto revise el query:

```
Sacando un reporte de Oficio... como de su nota recibida (respuesta) me genera solo la nota oficio enviada y no la respuesta, en este caso se busco en Oficio:(Empresa: ofep), y nota recibida: (remitente: Ana), deberia haber 3 notas emitidas y 1 con respuesta, pero me sale solo las enviadas:
```

![imagen](https://user-images.githubusercontent.com/25138642/62135642-924cb680-b2b0-11e9-81ab-46f3f642a092.png)

**Comment by Angiegiovi** [comment]
La NOTA DE RESPUESTA es esta seccion:
![Captura de pantalla de 2019-09-02 22-05-04](https://user-images.githubusercontent.com/25138642/64139162-ebd36400-cdcd-11e9-8ecd-9cd2243f4586.png)

Similar a las HR rosadas y celestes, existe registro y derivacion, igual en las notas oficio y comunicaciones internas hay dos secciones: notas enviadas y notas recibidas (respuesta a la nota enviada a la entidad)
El problema esta al generar el reporte, llenamos los datos de la nota enviada y tb de la recibida, sabiendo q si hay una nota recibida (respuesta) se hizo la prueba y solo genera notas enviadas no esta buscando por el lado de las recibidas.
