### ISSUE TITLE
Notas oficio de la Hoja de ruta:

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#30]
- debe jalar la columna de entidade/empresa de la base de datos de "empresas publicas" ya que esta existiendo muchas variaciones a la fecha.
![imagen](https://user-images.githubusercontent.com/25138642/62139435-56691f80-b2b7-11e9-96ce-f0c8b00ee016.png)

**Comment by caleeli** [comment]
Se agrego el llenado a partir de entidades/empresas:

![image](https://user-images.githubusercontent.com/8028650/64115141-d7a34e80-cd5c-11e9-93dc-72d874ce2f4f.png)
