### ISSUE TITLE
Boton TERMINAR de registro HR

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#36]
- El boton TERMINAR, que se encuentra en registro de hoja de ruta, debe Inhabilitar los campos del registro, y tb bloquear el boton guardar cambios, no solo ocultar derivaciones como ya se hizo.
En su lugar, el boton "terminar " se convierte en HABILITAR, cuando ya esta terminada la HR.
![imagen](https://user-images.githubusercontent.com/25138642/66611923-f54ea980-eb8d-11e9-92ce-8a34d4c1896c.png)

**Comment by caleeli** [comment]
- Se agrego el boton "Habilitar"
- Se deshabilitaron los botones y cajas de texto cuando la hoja esta terminada

![image](https://user-images.githubusercontent.com/8028650/66650959-de489f80-ebff-11e9-9fc7-834612cdf045.png)
