### ISSUE TITLE
Derivacion vacia

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#37]
- No debe salir este error al registrar una derivacion vacia. Si se podria colocar un mensaje para incluir un destinatario, nada mas o lo que sea pero no el mensaje con SQL…. q parece mas algo complicado a la vista del usuario final.

![imagen](https://user-images.githubusercontent.com/25138642/66612084-9178b080-eb8e-11e9-8f6b-a342017d8763.png)

No hay “derivaciones” sin un “destinatario” como en esta imagen se ve:
![imagen](https://user-images.githubusercontent.com/25138642/66612103-ae14e880-eb8e-11e9-8515-ee61d64c4e04.png)

**Comment by caleeli** [comment]
Se coloco destinatarios como requerido:

![image](https://user-images.githubusercontent.com/8028650/66651391-e5bc7880-ec00-11e9-92c6-550d1198e37f.png)
