### ISSUE TITLE
error al registrar Comunicaciones Internas

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#40]
Al registrar una comunicacion solo debe validar los campos del registro no asi de la "comunicacion recbida" que se encuentra mas abajo del registro... estos dos se separan .... en este momento cuando quiero registrar tambien me pide q se llene los campos de la comunicacion recibida. 
![imagen](https://user-images.githubusercontent.com/25138642/66654338-fd4b2f80-ec07-11e9-87de-3c82a6219c03.png)

**Comment by caleeli** [comment]
Muy bien, entonces se quitarán los requeridos de la sección comunicación recibida ya que no son requeridos

**Comment by caleeli** [comment]
![image](https://user-images.githubusercontent.com/8028650/66718213-5acdb080-edaf-11e9-9fda-c0b98bee5fba.png)
