### ISSUE TITLE
Limitar seleccion de destinatario

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#41]
la seleccion de destinatario debe ser solo para EDINO CLAVIJO, ROXANA DUARTE, KATHERINE GUIBARRA Y GASTON PIZARROSO Y CINTHIA MENDIETA, aqui no entra ADMIN ni ARCHIVO, en la seleccion de las ventanas: registro de correspondencia http://doc.scepinfoempresas.com/#/HojaRuta/create y registro de informes http://doc.scepinfoempresas.com/#/Informe/create
![Captura de pantalla de 2019-10-11 09-39-01](https://user-images.githubusercontent.com/25138642/66659316-45228480-ec11-11e9-8b55-919657b0a41a.png)

**Comment by caleeli** [comment]
Se agrego una columna "reservado" en la tabla de usuarios para filtrar aquellos usuarios (como admin y archivo) que no queremos que aparesca.

![image](https://user-images.githubusercontent.com/8028650/66718285-3de5ad00-edb0-11e9-82cd-ab58ef6a7c84.png)

**Comment by Angiegiovi** [comment]
Todavia esta Archivo entre los destinatarios:

![Captura de pantalla de 2019-10-14 09-28-09](https://user-images.githubusercontent.com/25138642/66754929-0d137f80-ee65-11e9-9bb9-8c183522aacf.png)
