### ISSUE TITLE
editar Seguimiento

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#43]
Se hara algo similar a Empresas Públicas
![imagen](https://user-images.githubusercontent.com/25138642/67051378-e7a6a000-f108-11e9-9149-f026afa5e05f.png)
**_A)_**
- el boton de editar PRIORIDAD, solo lo puede editar una persona con rol 1. 

OCULTAR:

- Barra de avance
- Subir Archivos

CAMBIAR NOMBRE:
- Creación --> Fecha de Derivación
- Creado por:   (la persona q asigno la tarea)

AGREGAR:
- text input "Recibidos" (acepte numeros 5 digitos)
- text input "Atendidos" (acepte numeros 5 digitos)

![imagen](https://user-images.githubusercontent.com/25138642/66779973-a9597880-ee9d-11e9-9b41-e1804411e12e.png)

**_B)_**

*** La pestaña 1.** "Atención a la Derivación"  nunca se deshabilita como en SUBCEP  que cuando presionamos "COMPLETADO" pasa a la siguiente pestaña, en este caso y debido a q tenemos que agregar mas usuario a una sola tarea, y ademas que los gerents se pierden al dar la calificacion, es q eliminamos la pestana calificacion, y movemos donde aparece los usuarios, podriamos mover todo a una sola pestaña y asignar la calificacion al lado del nombre. claro q este campo solo se habilita cuando el usuario termina la tarea (es decir pasa a completado)
![imagen](https://user-images.githubusercontent.com/25138642/67695966-60fd8880-f97c-11e9-8004-72fecd129fbc.png)

AHORA LOS ESTADOS>

- Estado Inicial: PENDIENTE (aun lo tiene el usuario asignado)
- Estado final del usuario asignado: COMPLETADO (el usuario da por terminada su tarea, frena el reloj de dias por completar, cambia de color y a pesar q aun puede editar sus comentarios, se habilita la opcion de calificacion del revisor (admin), esto no es editable ni para registro del usuario q completo la tarea)
- Estado Final: APROBADO (es cuando el usuario admin le da una calificacion al o a varios trabajos, y le da por aprobado)
 Este estado se debe reflejar tambien en Hoja de Ruta, en la columna "estado"

Reglas: 
1. cuando el usuario "complete" su tarea (ej. JAHEL BARRON),  automaticamente se pasa como derivado al que se le asigno en la HOJA DE RUTA... (ej. ROXANA DUARTE (rol1)) Este paso es automatico en la HR (esto no quiere decir que Roxana Duarte haya "completado" la tarea aqui creamos una alarma para Roxana indicando que tiene un pendiente de revision para aprobar, ver ticket #84 ) En realidad el estado aprobrado se atribuye al usuario (jahel) que hizo la tarea, esto cuenta para la generacion de reportes.

2. debe permitirme asignar dos o mas personas a la vez una tarea.... esto desde la derivacion de tarea hasta el seguimiento (como en subcep) ya que se estan dando muchas derivaciones dobles.... esto implica q cuando la tarea esta asignada a dos personas... cada una pueda loguearse con su usuario anotar su avance y cualquiera de ambos poder completar para q los aprueben, pero el nombre del usario q comento debe quedar registrado como acutalmente se lo hace con un usuario. La evaluacion se la asigna por usuario como ahora esta en la barra superior se habilitan las calificaciones para ambos, y en el reporte debe mostrar solo las calificaciones y completados por usuario no juntos.

3. El hecho de "COMPLETAR" la tarea, significa q suma un estado superado para el usuario... de modo que cuando busquemos en el **reporte**... tambien tenga esa opcion de "COMPLETADOS" donde deberian salir todos los completados de cada usuario, y no solo rescatar el ultimo estado. 

***estos estados deben mostrarse a la par en el estado de la Hoja de ruta***
ver ticket #65  donde se indica el boton terminar q estados muesta

**Comment by caleeli** [comment]
Se realizaron lo siguientes cambios:

- el boton de editar PRIORIDAD, solo lo puede editar una persona con rol 1.
- ocultar
  - Barra de avance
  - Subir Archivos
- CAMBIAR NOMBRE: Creación --> Fecha de Derivación
- AGREGAR:
  - text input "Recibidos" (acepte numeros 5 digitos)
  - text input "Atendidos" (acepte numeros 5 digitos)

**Comment by Angiegiovi** [comment]
Ok completado el inciso A, queda pendiente que desaparezca esta barra en el menu de tareas asignadas:

![imagen](https://user-images.githubusercontent.com/25138642/67696660-a4a4c200-f97d-11e9-9d4e-0cf94c753d00.png)

**Comment by Angiegiovi** [comment]
queda pendiente el cambio del inciso B, es un poco largo, pero es necesario porque estan quedando mal las tareas y causa mucha confusion e incluso problemas con las registradoras... tomar en cuenta el ticket #60  porq ahi explicamos un 4to rol detectado.

**Comment by Angiegiovi** [comment]
Revisando en el ambiente de pruebas, la hr 27527 contiene dos derivaciones, pero cuando se desea completar la tarea con el usuario dcanelas, no realiza el completado.
Lo correcto seria que se complete por parte de ese usuario y su reloj deje de seguir pasando los dias y tnga una fecha., mientras que el otro usuario deberia poder terminar y a la vez Completar la tarea.
este cambio va junto con el ticket #65 
![imagen](https://user-images.githubusercontent.com/25138642/68418977-bd785900-016f-11ea-83fd-6bf5aebe0a59.png)

**Comment by caleeli** [comment]
@Angiegiovi podrias aclarar cual es el funcionamiento correcto, hablando por telefono me dijiste que si la tarea tenia dos usuarios asignados:

1. Cuando uno de los usuarios (cualquiera) completaba la tarea, se completa para ambos, es decir la tarea se completa.

Pero en la siguiente nota dices:
> Lo correcto seria que se complete por parte de ese usuario y su reloj deje de seguir pasando los dias y tnga una fecha., mientras que el otro usuario deberia poder terminar y a la vez Completar la tarea.

2. Lo que entiendo de esa nota es: que si un usuario termina se completa la parte de ese usuario, para ese usuario se congela el reloj, pero la tarea sigue pendiente hasta que el segundo usuario Completa finalmente la tarea.

Por favor déjame claro **por escrito** cuál será el comportamiento correcto y final (1 o 2 o si es de otra forma) Por favooor dejalo claro ya estoy cambiando este comportamiento cada vez. Por favor documenta casos de uso para esta funcionalidad (Por ejemplo: caso 1 cuando hay un asignado como se termina, caso 2 cuando hay dos asignados cuando uno termina, etc)

> Revisando en el ambiente de pruebas, la hr 27527 contiene dos derivaciones, pero cuando se desea completar la tarea con el usuario dcanelas, no realiza el completado.
> Lo correcto seria que se complete por parte de ese usuario y su reloj deje de seguir pasando los dias y tnga una fecha., mientras que el otro usuario deberia poder terminar y a la vez Completar la tarea.
> este cambio va junto con el ticket #65
> ![imagen](https://user-images.githubusercontent.com/25138642/68418977-bd785900-016f-11ea-83fd-6bf5aebe0a59.png)

**Comment by caleeli** [comment]
Se agrego el listado de solo **tareas completadas** para el usuario con rol 1 (Admin) y que este pueda **Terminarlas**

![image](https://user-images.githubusercontent.com/8028650/70323104-4ed7fb00-1802-11ea-9076-325702e4a0e1.png)


> cuando el usuario "complete" su tarea (ej. JAHEL BARRON), automaticamente se pasa como derivado al que se le asigno en la HOJA DE RUTA... (ej. ROXANA DUARTE (rol1)) Este paso es automatico en la HR (esto no quiere decir que Roxana Duarte haya "completado" la tarea aqui creamos una alarma para Roxana indicando que tiene un pendiente de revision para aprobar, ver ticket #84 ) En realidad el estado aprobrado se atribuye al usuario (jahel) que hizo la tarea, esto cuenta para la generacion de reportes.

**Comment by Angiegiovi** [comment]
1. Si esta bien las campanas para los de rol 1. sin embargo las campanas no se actualizan cada que se aprueba las tareas. 
2. no deberia aprobar si no se califica.
3. al aprobar se queda en la pantalla, deberia ir a la lista donde le bota la campana

**Comment by caleeli** [comment]
1. Se actualiza el contador de la campana después de aprobar
2. Se verifica que se hayan calificado antes de aprobar
3. Después de aprobar se va al listado de la campana

![image](https://user-images.githubusercontent.com/8028650/70842631-7d566700-1dfc-11ea-8f6a-2ae49a4e7276.png)


> 1. Si esta bien las campanas para los de rol 1. sin embargo las campanas no se actualizan cada que se aprueba las tareas.
> 2. no deberia aprobar si no se califica.
> 3. al aprobar se queda en la pantalla, deberia ir a la lista donde le bota la campana

**Comment by Angiegiovi** [comment]
1. se comprobo que la campana no se actualiza al aprobar. 
2. aprueba sin calificar.
3. si se va al listado pero no precisamente a los que les falta su calificacion.

**Comment by caleeli** [comment]
Se probo con rduarte y se ve que se esta validando y actualizando.
Tal vez podrias probar limpiar cache.

![campanita](https://user-images.githubusercontent.com/8028650/70993446-705aa180-20a2-11ea-9d57-a2c8fa800652.gif)

**Comment by Angiegiovi** [comment]
ESTA BIEN.
