### ISSUE TITLE
campo Abierto

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#46]
el campo PROCEDENCIA del registro de Hoja de ruta, debe ser un campo abierto, es decir que si nohay en la base de datos el nombre de la entidad, sea posible agregar y q esa misma se guarde en la tabla entidad con ent_clasificador  que empiece en con 001 y no repita a los numeros ya existentes. 

![Captura de pantalla de 2019-10-14 23-09-55](https://user-images.githubusercontent.com/25138642/66797333-67015d00-eed8-11e9-9ae2-f842d1d3b9c0.png)

**Comment by Angiegiovi** [comment]
adjunto codigo sql para la creación de un nuevo registro cuando transcriban la nueva entidad, es decir cuando no haya opcion de las entidades... debemos agregar nueva entidad q no tiene clasificador.

[adm_entidad_sinclasificador.zip](https://github.com/caleeli/documentos/files/3735967/adm_entidad_sinclasificador.zip)

**Comment by Angiegiovi** [comment]
Para el caso de entidades de la CGE crearé una base de datos esas aplican para hr rosadas

**Comment by caleeli** [comment]
Se agrego un boton para agregar entidades

![image](https://user-images.githubusercontent.com/8028650/67017426-c8d3e980-f0c7-11e9-8565-c89444c199e7.png)
