### ISSUE TITLE
Modificación de tipo de Hoja de Ruta

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#47]
Por temas de entendimiento del personal de registro, se cambiuara el denominativo:

- EXTERNAS
- INTERNAS
- SOLICITUDES Y/O DENUNCIAS

 por lo siguiente:

- EXTERNAS  -- CELESTES
- INTERNAS -- ROSADAS
- SOLICITUDES Y/O DENUNCIAS -- AMARILLAS

Este cambio se debe ver en:
*Registro de Hoja de Ruta 
*selección de reportes
* en el resultado de reportes 
![imagen](https://user-images.githubusercontent.com/25138642/66839730-e290f780-ef34-11e9-9050-275989c9ca6c.png)

![imagen](https://user-images.githubusercontent.com/25138642/66839709-d7d66280-ef34-11e9-94ec-99d084eb1f32.png)

![imagen](https://user-images.githubusercontent.com/25138642/66839945-3c91bd00-ef35-11e9-9f6d-2647564ac399.png)

Si implicara muchos cambios internos, solo se debe cambiar en las pantallas de vista al usuario,

**Comment by Angiegiovi** [comment]
solo falta el cambio de la denomicacion en los reportes:
![imagen](https://user-images.githubusercontent.com/25138642/69645011-d3c15880-103b-11ea-934a-94e36f7f3693.png)

**Comment by caleeli** [comment]
Se corrigió la denominación de los tipos de reporte.

![image](https://user-images.githubusercontent.com/8028650/70842970-02dc1600-1e01-11ea-97c6-59901a461e43.png)

**Comment by Angiegiovi** [comment]
OK, favor pasar a produccion
