### ISSUE TITLE
registro de Hoja de Ruta INTERNA

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#50]
no esta mostrando la clasificacion de HR interna, si me muestra de externa y sol.y/o denuncias. pero no de interna.

Ahora cambia el denominatvo a colores.

![imagen](https://user-images.githubusercontent.com/25138642/67105213-57af3780-f196-11e9-8b6d-7a42f88b5ecf.png)

**Comment by caleeli** [comment]
Favor verificar,

![image](https://user-images.githubusercontent.com/8028650/67201737-e610fc80-f3d4-11e9-8d27-1639fed6090c.png)
