### ISSUE TITLE
base de datos CGE

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#55]
crear una opcion igual al de entidades (con clasificador) adjunto el mismo

en Hoja de Ruta. esta misma debe ser insumo para todos los campos de **procedencia y detinatario** de informes, notas, comunicaciones, reportes y ademas la derivacion de las Hojas de rutas
[adm_cge.zip](https://github.com/caleeli/documentos/files/3740877/adm_cge.zip)

![imagen](https://user-images.githubusercontent.com/25138642/67039883-4f9cbc80-f0f0-11e9-9964-919667dafecc.png)

**Comment by caleeli** [comment]
Se agrego el registro CGE Interno:

![image](https://user-images.githubusercontent.com/8028650/67088206-8d422980-f172-11e9-88c2-d9af46bf0740.png)
