### ISSUE TITLE
agregar una opcion en la clasificacion

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#57]
una cuarta opcion en la clasificacion del registro de la hoja de ruta:

4. SCSL 
    - Comunicaciones Internas
    - Informes
    - Notas Oficio 
![imagen](https://user-images.githubusercontent.com/25138642/67089556-ee1f3100-f175-11e9-9156-f0d6ab723070.png)

ya existe una clasificacion en la tabla
![imagen](https://user-images.githubusercontent.com/25138642/67089684-41917f00-f176-11e9-878a-dfa6b4871d2a.png)
y su subclasificacion

![imagen](https://user-images.githubusercontent.com/25138642/67089875-a8169d00-f176-11e9-9378-8618d2640910.png)

**Comment by Angiegiovi** [comment]
adicionalmente pidieron se incluya mas opciones para la opcion 3. GAAJ, esta subclsificacion ya esta en la base de datos.

![imagen](https://user-images.githubusercontent.com/25138642/67163714-502b9200-f340-11e9-8de9-6bcf8e668fef.png)

**Comment by caleeli** [comment]
![image](https://user-images.githubusercontent.com/8028650/67214597-026d6300-f3ee-11e9-819d-a5d169fbc01e.png)

**Comment by Angiegiovi** [comment]
ok
