### ISSUE TITLE
agregar un campo

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#59]
agregar dos opciones: Folder y Sobres

![imagen](https://user-images.githubusercontent.com/25138642/67166425-47958480-f35d-11e9-8bcc-28cb6af31f97.png)

**Comment by caleeli** [comment]
Se agrego las opciones requeridas:

![image](https://user-images.githubusercontent.com/8028650/67290991-d9f96d80-f4ae-11e9-9328-57901036090c.png)
