### ISSUE TITLE
medidor de tarea

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#63]
1. Comentar el medidor de tarea, ya no debe aparecer en el seguimiento, pero no borrrar si acaso lo subimos mas adelante.

![imagen](https://user-images.githubusercontent.com/25138642/67265290-5d996700-f47b-11e9-9d7d-e4e2a1fa669a.png)

2. Se debe unir las tareas a una sola Hoja de ruta, como en subcep. Los usuarios deben verse en una misma tarea de acuerdo a las asignaciones.

![imagen](https://user-images.githubusercontent.com/25138642/67396450-9ddd1000-f575-11e9-9e41-98c7165cb4a1.png)

3.  La calificacion debe ir por usuario, podriamos mover todo a una sola pestaña y asignar la calificacion al lado del nombre. claro q este campo solo se habilita cuando el usuario termina la tarea (ticket #43)

![imagen](https://user-images.githubusercontent.com/25138642/67396601-de3c8e00-f575-11e9-8023-8897f8f9a13f.png)

**Comment by caleeli** [comment]
Se removio la barra de progreso
![image](https://user-images.githubusercontent.com/8028650/67638579-76ab7900-f8bc-11e9-9df2-066d9c9050ee.png)

**Comment by Angiegiovi** [comment]
se cierra porq se completo las anotaciones en el ticket 43, en donde se une estas observaciones para entender mejor.
