### ISSUE TITLE
Urgente, 23 de octubre 

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#64]
1. Comunicaciones internas:
- numero de hoja de ruta no está jalando las hr de los registrados 
- gerencia/Subcontraloria -este campo debe jalar de la tabla adm-cge

![imagen](https://user-images.githubusercontent.com/25138642/67424437-1f4b9700-f5a4-11e9-8018-52c08db74ed9.png)

2. Habilitar el campo de seguimiento para q se pueda editar los comentarios... estos tb deben ser editables
![imagen](https://user-images.githubusercontent.com/25138642/67424271-d1cf2a00-f5a3-11e9-86cd-c7ef01ea8aa3.png)

**Comment by Angiegiovi** [comment]
3. Las derivaciones para mas de un usuario las estan registrando de esta manera:
![imagen](https://user-images.githubusercontent.com/25138642/67429334-f03a2300-f5ad-11e9-8559-ae93dffaa04e.png)

Sin embargo, en el seguimiento no se ve la derivacion: 
![imagen](https://user-images.githubusercontent.com/25138642/67429379-08aa3d80-f5ae-11e9-8414-63e06a33c198.png)
 algo paso q no esta mostrando en el seguimiento esta HR. para ello se penso hacer algo similar a sucep : ticket #63 punto 2

**Comment by caleeli** [comment]
Se corrigio el punto 1, listado de hojas de ruta

**Comment by Angiegiovi** [comment]
Sobre el punto 1. el primer campo de HR si jala de la bd. pero el siguiente campo no esta buscando gerencias ni subcontralorias unicamente jala Subonctraloria de Servicios LEgales.

![imagen](https://user-images.githubusercontent.com/25138642/67494565-60e14e00-f647-11e9-8ea2-6374c41eb8f4.png)

**Comment by Angiegiovi** [comment]
Favor priorizar el punto 
2. Habilitar el campo de seguimiento para q se pueda editar los comentarios... estos tb deben ser editables (como ejemplo una tarea de Ariel Berrios)

**Comment by caleeli** [comment]
Se agrego la funcionalidad para editar comentarios:

![image](https://user-images.githubusercontent.com/8028650/67638194-47930880-f8b8-11e9-984c-da0dd0dd6c8e.png)

![image](https://user-images.githubusercontent.com/8028650/67638202-58437e80-f8b8-11e9-8646-39118f4f85c9.png)

**Comment by Angiegiovi** [comment]
el punto 2 si se soluciono, hay un error que aun esta presente, lo comente de forma verbal: el puntaje solo lo pueden dar: CYNTIA MENDIETA, CATHERINE GUIBARRA, ROXANA DUARTE, PIZARROSO, Y EDINO CLAVIJO

![imagen](https://user-images.githubusercontent.com/25138642/67679962-b1ff8380-f960-11e9-9e9c-55a1dba1fe24.png)

**Comment by Angiegiovi** [comment]
Todo OK
