### ISSUE TITLE
Derivacion Hoja de Ruta #1 

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#73]
la derivacion es muy confusa, por lo que al insertar el segundo derivado pareciera q se borro el primero. se debe quedar el primero q derivamos con una X para eliminar uno por uno, luego respetar el un espacio y poder agregar el segundo.
 
![imagen](https://user-images.githubusercontent.com/25138642/68726276-53105000-0597-11ea-82bd-a3ea99610468.png)

**Comment by caleeli** [comment]
Se realizo la corrección
![seleccion destinatarios](https://user-images.githubusercontent.com/8028650/70622387-3563f400-1bf2-11ea-95f9-349c0382eef5.gif)

**Comment by caleeli** [comment]
Se mejoro la alineación del texto, y se limpian las iniciales cada vez que se selecciona un valor.

![image](https://user-images.githubusercontent.com/8028650/70843127-8565d500-1e03-11ea-93b1-c30075805d08.png)

**Comment by Angiegiovi** [comment]
Correcto, pasar a produccion
