### ISSUE TITLE
Seguimiento (5)

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#76]
en hoja de ruta se le asigno asi: 
se elimino la primera derivacionq era a javier landa

![imagen](https://user-images.githubusercontent.com/25138642/68730443-1ea29100-05a3-11ea-8f8b-fd9dccb7e9dd.png)

pero en el seguimiento aparece asi:
![imagen](https://user-images.githubusercontent.com/25138642/68730515-4d206c00-05a3-11ea-8dfe-640b0bf281ae.png)

si eliminamos debe estar reflejado en el seguimiento....  ese es el error.

**Comment by Angiegiovi** [comment]
Se hizo la revisión: 
1. ya se elimina correctamente (HR -27703), sin embargo...
![imagen](https://user-images.githubusercontent.com/25138642/70805904-72fe8380-1d90-11ea-8c07-3aec615417e9.png)
despues de eliminar:
![imagen](https://user-images.githubusercontent.com/25138642/70805948-8873ad80-1d90-11ea-9af6-196e76653c32.png)

2. pero en seguimiento si bien se elimina el nombre del derivado, no se borra del todo la tarea derivada, quedando de la siguiente forma
![imagen](https://user-images.githubusercontent.com/25138642/70805856-53fff180-1d90-11ea-98b7-bf9296d36ab4.png)

**Comment by caleeli** [comment]
Se corrigió para que al eliminar todas las asignaciones también se elimina la tarea.

**Comment by Angiegiovi** [comment]
Si se corrigio en el caso de solo un asignado, pero las que son de dobles asignaciones aun estan con problemas:
1. se asignaron a dos personas: Ariel Rios, Javier Rolando, Cristiam Gonzales
2. se elimino a Cristiam Gonzales
![imagen](https://user-images.githubusercontent.com/25138642/70878246-0f927280-1f97-11ea-9c28-a38f35c06e62.png)

3. pero en el seguimiento continua el que se elimino:
![imagen](https://user-images.githubusercontent.com/25138642/70878266-25a03300-1f97-11ea-85e6-37718c6cf5c6.png)

4. Ademas la edicion del seguimiento no muestra la X para eliminar el primer agregado, el campo solo senala a los dos primeros derivados pero algo dificil de entender.
![imagen](https://user-images.githubusercontent.com/25138642/70878346-7fa0f880-1f97-11ea-99bb-4ecdf0759592.png)

**Comment by caleeli** [comment]
- Se corrigió la actualización de destinatarios en la hoja de ruta y en el seguimiento.
- Se arreglo el componente para seleccionar opciones.

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/8028650/71360718-160c8580-2567-11ea-9669-f51339ea1056.gif)

**Comment by Angiegiovi** [comment]
Ahora el problema es que aun aparece esa tarea en la bandeja de Cristiam,  a pesar que se elimino: lo q se hizo es asignar la hr 27703 una derivacion a ariel rios y cristiam gonzales, se elimino a cristiam, y el seguimiento solo muestra a ariel rios. Sali y entre con el usuario de cristiam (cgonzales - 2280811)  y la tarea esta en su bandeja como pendiente sin que estuviese su nombre en la lista:
 la primera asignación se probo hr 27703

![imagen](https://user-images.githubusercontent.com/25138642/71416166-c052de80-2635-11ea-9556-f85934560cee.png)

**Comment by caleeli** [comment]
Se corrigió el query para filtrar las tareas que ya no están asignadas al usuario

![image](https://user-images.githubusercontent.com/8028650/71495112-93afea00-2822-11ea-9592-37cd0520290a.png)

**Comment by Angiegiovi** [comment]
pasar a produccion
