### ISSUE TITLE
buscador de seguimiento

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#82]
Con el usuario cveizaga se probo entrar a seguimiento:
![imagen](https://user-images.githubusercontent.com/25138642/69637649-77583c00-102f-11ea-80cb-b40c8f46dab7.png)

pero si buscamos "mendienta" en el buscador, me da las tareas de este usuario, algo que no deberia ocurrir, porq los usuarios solo pueden ver tareas de ellos mismos.

![imagen](https://user-images.githubusercontent.com/25138642/69637947-1846f700-1030-11ea-9852-5ad54e49136d.png)

**Comment by caleeli** [comment]
Se corrigio la busqueda y filtrado de tareas en seguimiento

**Comment by Angiegiovi** [comment]
ok pasar a producción
