### ISSUE TITLE
agregar alarmas

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#84]
Se creara campanitas estilo Gmail, para indicar los pendientes de aprobacion a los gerentes y responsables de unidad, solo debe indicar el numero y la lista en el seguimiento

**Comment by caleeli** [comment]
![image](https://user-images.githubusercontent.com/8028650/70323104-4ed7fb00-1802-11ea-9076-325702e4a0e1.png)

**Comment by Angiegiovi** [comment]
OK
