### ISSUE TITLE
registros en la BD

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#90]
los registros se modifican cuando lo eliminamos? pense q solo se agregaba la fecha de eliminacion y quedaba eliminado el registro. por ejemplo el de la imagen
![imagen](https://user-images.githubusercontent.com/25138642/70812118-60d71200-1d9d-11ea-92cc-47430f4bb62b.png)

**Comment by caleeli** [comment]
@Angiegiovi, al eliminar solo se llena la fecha de eliminación con lo cual se los considera como eliminados

**Comment by caleeli** [comment]
No entiendo bien tu pregunta, me podrias indicar que esta mal en la imagen?

- Dices que no deberia aparecer el registro con fecha de eliminacion en la base de datos? Si fuera esto, a esto se le llama eliminacion logica, que quiere decir que el registro permanece en la base de datos marcado como eliminado (en este caso por el campo de fecha de eliminacion). A diferencia de una eliminacion fisica donde el registro se elimina de la base de datos, por lo cual tampoco existiria la fecha de eliminación ya que el registro ya no existiria y no sería posible almacenar ese datos para un registro que ya no existe

**Comment by Angiegiovi** [comment]
Mi pregunta es por que el campo de instruccion aparece null, si se qusiera rastrear no sabriamos q instruccion se le dio antes de borrar.... esto sucede solo porq el campo instruccion crea una derivacion?
ahora esta como null-- a eso le llamo modificacion al eliminar... q si elimino cambia su instruccion... tu me dices q solo deberia de aparecer la fecha de eliminacion en esa misma columna.

**Comment by caleeli** [comment]
@Angiegiovi  Se reviso y verificó que solo el campo "deleted_at" que se llena con una fecha al ser eliminada, y deja el resto con el valor que tenian. Que ese campo (instruccion) aparece en null, significa que no se lo habia llenado al hacer la derivación al principio.

**Comment by Angiegiovi** [comment]
OK
