### ISSUE TITLE
Algunos arreglos

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#92]
![imagen](https://user-images.githubusercontent.com/25138642/71000027-f2ea5d80-20b0-11ea-9424-a8f1337e1479.png)
 Aqui solo yo entiendo q fue creado por marlene y derivado por marlene, por favor podriamos separarlos en dos filas:

Creado por: Marlene Medrano hace 5 horas
Derviado por: Marlene Medrano hace 5 horas

Talves los iconos podrian permanecer, el ultimo icono no se si es de edición o derivacion. si fuese asi tb deberia tener un "editado por: " ya hubo problemas con el registro y edición.

**Comment by caleeli** [comment]
Se realizo el ajuste:
![image](https://user-images.githubusercontent.com/8028650/71138844-17465700-21e3-11ea-9107-88433dfb1512.png)

**Comment by Angiegiovi** [comment]
ok pasar a produccion
