### ISSUE TITLE
Limitar Destinatarios

### ISSUE THREAD

**Issue by Angiegiovi** [caleeli/documentos#93]
Al registrar la Hoja de Ruta solo deben aparecer los nombres de EDINO CLAVIJO, CINTHIA MENDIETA, ROZANA DUARTE, KATHERINE GUIBARRA, GASTÓN PIZARROSO, en el campo: Destinatario(*)   de la hoja de ruta únicamente.

**Comment by caleeli** [comment]
Se realizo el ajuste:
![image](https://user-images.githubusercontent.com/8028650/71085480-014a7f00-216e-11ea-9972-8e35f42f6c7b.png)

**Comment by Angiegiovi** [comment]
ok, pasar a produccion
